# Makefile for CSE5462 lab

default: Drone.c DefineValue.h InputUtility.h GridUtility.h 
	gcc -g -Wall -o Drone DefineValue.h InputUtility.h GridUtility.h Drone.c -lm

c:
	clear
	
clean:
	rm -f Drone
